### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lhan0903** [lhan0903/DSCI-100-Project-006-26#1]
### Reminder: fix these before we submit final report (from TA feedback on project proposal)

- [x] Overall really well done. Just make sure that you read the data from the web, not locally!

- [ ] Comments are good too, I would consider adding even more of them

- [ ]  Go more into depth on why you think these variables will be able to be used to differentiate species!

- [ ] Some spelling/grammar fixes need to be made but overall this is well-written.

**Comment by lhan0903** [comment]
### Linda's Tasks

- [ ] describe in written English the methods you used to perform your analysis from beginning to end that narrates the code the does the analysis.

**your report should include code which:**

- [x] loads data from the original source on the web 

- [x] wrangles and cleans the data from it's original (downloaded) format to the format necessary for the planned analysis

- [x] performs a summary of the data set that is relevant for exploratory data analysis related to the planned analysis 

- [x] creates a visualization of the dataset that is relevant for exploratory data analysis related to the planned analysis

- [ ] performs the data analysis

- [ ] creates a visualization of the analysis 

note: all tables and figure should have a figure/table number and a legend
